// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApplication1.Models
{
    public partial class TravelContext : DbContext
    {
        public TravelContext()
        {
        }

        public TravelContext(DbContextOptions<TravelContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Place> Place { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Place>(entity =>
            {
                entity.Property(e => e.PlaceId)
                    .HasMaxLength(10)
                    .HasColumnName("PlaceID");

                entity.Property(e => e.Add).HasMaxLength(150);

                entity.Property(e => e.Closetime).HasMaxLength(5);

                entity.Property(e => e.Description).HasMaxLength(500);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Opentime).HasMaxLength(5);

                entity.Property(e => e.Region)
                    .IsRequired()
                    .HasMaxLength(3);

                entity.Property(e => e.Tel).HasMaxLength(12);

                entity.Property(e => e.Town)
                    .IsRequired()
                    .HasMaxLength(4);
            });

            OnModelCreatingGeneratedFunctions(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}